 DELIMITER $$
 CREATE FUNCTION SOMA_CLIENTES(DATA_HOJE DATE)
 RETURNS DATE
 BEGIN
	SELECT SUM(CLIENTES_CADASTRADOS) AS 'TOTAL_CLIENTES_CADASTRADOS' FROM CLIENTES
	WHERE DATA_HOJE = CURRENT_DATE();
 END
 $$